services:
  envoy:
    image: envoyproxy/envoy:dev-c8f58b61c36dbbd37d92f9826a90288136897df9
    ports:
      - "10000:10000"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml

  app:
    build:
      context: app
